### ISSUE TITLE
Iron trapdoors not displaying redstone lamps

### ISSUE THREAD

**Issue by adamondr** [Xyverle/MattPack#2]
MBW said in this video (https://youtu.be/cSK4NMJj44w) that he retextured iron trapdoors to look like redstone lamps, but its not working for me.

**Comment by Xyverle** [comment]
Are you sure you are using the correct branch?
Are you sure that you are placing the trapdoors on the top half?

**Comment by taciturnaxolotl** [comment]
Use the trapdoor lamp branch. [https://github.com/Xyverle/MattPack/tree/trapdoor-lamp](https://github.com/Xyverle/MattPack/tree/trapdoor-lamp)
